# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)





Book.create(:jpgno => 1, :name => "ベイシス数学", :price => 972, :publisher => "河合出版", :level => 1, :hands => 2, :layout => 2, :const => 5, :page => 352)
Book.create(:jpgno => 2, :name => "10日あればいい（黄緑）", :price => 724, :publisher => "実教出版", :level => 1, :hands => 2, :layout => 3, :const => 3, :page => 142)
Book.create(:jpgno => 3, :name => "これでわかる問題集", :price => 1026, :publisher => "文英堂", :level => 1, :hands => 2, :layout => 4, :const => 2, :page => 264)
Book.create(:jpgno => 4, :name => "ホントはやさしいシリーズ", :price => 950, :publisher => "文英堂", :level => 1, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 5, :name => "はじめからていねいに", :price => 1296, :publisher => "ナガセ", :level => 1, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 6, :name => "数学の点数が面白いほどとれる本", :price => 1296, :publisher => "中経出版", :level => 1, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 8, :name => "シグマ基本問題集", :price => 972, :publisher => "文英堂", :level => 2, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 9, :name => "カルキュール", :price => 918, :publisher => "駿台文庫", :level => 2, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 7, :name => "合格る計算", :price => 1080, :publisher => "文英堂", :level => 2, :hands => 2, :layout => 5, :const => 1, :page => 300)
Book.create(:jpgno => 10, :name => "一目でわかる数学ハンドブック", :price => 1296, :publisher => "ナガセ", :level => 2, :hands => 2, :layout => 4, :const => 3, :page => 300)
Book.create(:jpgno => 11, :name => "基礎問題精講", :price => 1188, :publisher => "旺文社", :level => 3, :hands => 2, :layout => 2, :const => 4, :page => 300)
Book.create(:jpgno => 12, :name => "数学の完全マスター", :price => 1188, :publisher => "文英堂", :level => 3, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 13, :name => "プレ1対1対応の演習", :price => 1080, :publisher => "東京出版", :level => 3, :hands => 2, :layout => 2, :const => 3, :page => 300)
Book.create(:jpgno => 14, :name => "チェック＆リピート", :price => 1080, :publisher => "Z会出版", :level => 3, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 15, :name => "チョイス新標準問題集", :price => 972, :publisher => "河合出版", :level => 3, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 16, :name => "チャート式入試必携168", :price => 1242, :publisher => "数研出版", :level => 3, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 17, :name => "BASIC", :price => 734, :publisher => "駿台文庫", :level => 3, :hands => 2, :layout => 4, :const => 4, :page => 132)
Book.create(:jpgno => 18, :name => "基本演習", :price => 1512, :publisher => "駿台文庫", :level => 3, :hands => 2, :layout => 2, :const => 5, :page => 257)
Book.create(:jpgno => 19, :name => "10日あればいい（黒）", :price => 724, :publisher => "実教出版", :level => 3, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 20, :name => "1対1対応の演習", :price => 1188, :publisher => "東京出版", :level => 4, :hands => 2, :layout => 2, :const => 1, :page => 120)
Book.create(:jpgno => 21, :name => "教科書Next", :price => 1620, :publisher => "東京出版", :level => 4, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 22, :name => "ハッと目覚める確率", :price => 1645, :publisher => "東京出版", :level => 4, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 23, :name => "数学1A標準問題精講", :price => 1296, :publisher => "旺文社", :level => 4, :hands => 2, :layout => 5, :const => 5, :page => 254)
Book.create(:jpgno => 24, :name => "数学2B標準問題精講", :price => 1555, :publisher => "旺文社", :level => 4, :hands => 2, :layout => 2, :const => 5, :page => 256)
Book.create(:jpgno => 25, :name => "数学12AB入試問題集文理系", :price => 1296, :publisher => "数研出版", :level => 4, :hands => 2, :layout => 1, :const => 4, :page => 119)
Book.create(:jpgno => 26, :name => "重要問題集", :price => 1209, :publisher => "数研出版", :level => 4, :hands => 2, :layout => 1, :const => 4, :page => 79)
Book.create(:jpgno => 27, :name => "スタンダード12AB受験編", :price => 0, :publisher => "数研出版", :level => 4, :hands => 2, :layout => 1, :const => 1, :page => 135)
Book.create(:jpgno => 28, :name => "理系数学良問プラチカ1A2B", :price => 1080, :publisher => "河合出版", :level => 4, :hands => 3, :layout => 2, :const => 5, :page => 54)
Book.create(:jpgno => 29, :name => "厳選大学入試数学問題集理系", :price => 1080, :publisher => "河合出版", :level => 4, :hands => 3, :layout => 3, :const => 4, :page => 86)
Book.create(:jpgno => 30, :name => "国立標準問題集 CanPass", :price => 1080, :publisher => "駿台文庫", :level => 4, :hands => 2, :layout => 1, :const => 5, :page => 57)
Book.create(:jpgno => 31, :name => "受験数学の理論", :price => 1080, :publisher => "駿台文庫", :level => 4, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 32, :name => "数学の計算革命", :price => 1566, :publisher => "駿台文庫", :level => 4, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 33, :name => "理系数学入試の核心", :price => 1080, :publisher => "Z会出版", :level => 4, :hands => 3, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 34, :name => "文系数学入試の核心", :price => 1296, :publisher => "Z会出版", :level => 4, :hands => 1, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 35, :name => "SPEED攻略10日間", :price => 648, :publisher => "Z会出版", :level => 4, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 36, :name => "新数学スタンダード演習", :price => 1650, :publisher => "東京出版", :level => 5, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 37, :name => "数学3スタンダード演習", :price => 1340, :publisher => "東京出版", :level => 5, :hands => 3, :layout => 2 , :const => 1 , :page => 132 )
Book.create(:jpgno => 39, :name => "この問題が合否を決める", :price => 1944, :publisher => "東京出版", :level => 5, :hands => 2, :layout => 2 , :const => 1 , :page => 232 )
Book.create(:jpgno => 40, :name => "合否を分けたこの1題", :price => 1340, :publisher => "東京出版", :level => 5, :hands => 2, :layout => 2 , :const => 1 , :page => 144 )
Book.create(:jpgno => 41, :name => "数学を決める論証力", :price => 1131, :publisher => "東京出版", :level => 5, :hands => 2, :layout => 2 , :const => 3 , :page => 104 )
Book.create(:jpgno => 38, :name => "微積分・基礎の極意", :price => 1337, :publisher => "東京出版", :level => 5, :hands => 3, :layout => 2 , :const => 2 , :page => 128 )
Book.create(:jpgno => 42, :name => "数学ショートプログラム", :price => 1080, :publisher => "東京出版", :level => 5, :hands => 2, :layout => 2 , :const => 3 , :page => 120 )
Book.create(:jpgno => 43, :name => "やさしい理系数学", :price => 1361, :publisher => "河合出版", :level => 5, :hands => 3, :layout => 3 , :const => 2 , :page => 135 )
Book.create(:jpgno => 44, :name => "文系数学良問プラチカ", :price => 1234, :publisher => "河合出版", :level => 5, :hands => 1, :layout => 3 , :const => 2 , :page => 336 )
Book.create(:jpgno => 45, :name => "大学入試攻略数学問題集", :price => 1050, :publisher => "河合出版", :level => 5, :hands => 2, :layout => 2 , :const => 2 , :page => 164 )
Book.create(:jpgno => 46, :name => "新こだわってシリーズ", :price => 885, :publisher => "河合出版", :level => 5, :hands => 2, :layout => 3 , :const => 3 , :page => 192 )
Book.create(:jpgno => 47, :name => "上級問題精講", :price => 1404, :publisher => "旺文社", :level => 5, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 48, :name => "探求と演習", :price => 1620, :publisher => "Z会出版", :level => 5, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 49, :name => "ハイレベル数学の完全攻略", :price => 972, :publisher => "駿台文庫", :level => 5, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 50, :name => "実戦演習", :price => 836, :publisher => "駿台文庫", :level => 5, :hands => 2, :layout => 2 , :const => 2 , :page => 352 )
Book.create(:jpgno => 51, :name => "理系標準問題集", :price => 1080, :publisher => "駿台文庫", :level => 5, :hands => 3, :layout => 2 , :const => 2 , :page => 234 )
Book.create(:jpgno => 52, :name => "入試数学の思考法", :price => 1296, :publisher => "駿台文庫", :level => 5, :hands => 2, :layout => 2 , :const => 3 , :page => 231 )
Book.create(:jpgno => 53, :name => "数学12AB入試問題集理系", :price => 1296, :publisher => "数研出版", :level => 5, :hands => 2, :layout => 1 , :const => 2 , :page => 112 )
Book.create(:jpgno => 54, :name => "数学3入試問題集", :price => 1296, :publisher => "数研出版", :level => 5, :hands => 3, :layout => 1 , :const => 2 , :page => 92 )
Book.create(:jpgno => 55, :name => "オリジナル・スタンダード3", :price => 0, :publisher => "数研出版", :level => 5, :hands => 2, :layout => 1, :const => 1, :page => 167)
Book.create(:jpgno => 56, :name => "新数学演習", :price => 1650, :publisher => "東京出版", :level => 6, :hands => 2, :layout => 3, :const => 3, :page => 168)
Book.create(:jpgno => 57, :name => "解法の探求・微積分", :price => 1512, :publisher => "東京出版", :level => 6, :hands => 3, :layout => 1, :const => 3, :page => 144)
Book.create(:jpgno => 58, :name => "解決へのアプローチ", :price => 1296, :publisher => "東京出版", :level => 6, :hands => 2, :layout => 2, :const => 3, :page => 135)
Book.create(:jpgno => 59, :name => "東大数学で1点でも多く取る方法理系編", :price => 2160, :publisher => "東京出版", :level => 6, :hands => 3, :layout => 3, :const => 5, :page => 479)
Book.create(:jpgno => 60, :name => "東大数学で1点でも多く取る方法文系編", :price => 1512, :publisher => "東京出版", :level => 6, :hands => 1, :layout => 3, :const => 5, :page => 260)
Book.create(:jpgno => 61, :name => "解法の突破口", :price => 1620, :publisher => "東京出版", :level => 6, :hands => 2, :layout => 4, :const => 5, :page => 215)
Book.create(:jpgno => 62, :name => "解法の探求・確率", :price => 1296, :publisher => "東京出版", :level => 6, :hands => 2, :layout => 2, :const => 3, :page => 128)
Book.create(:jpgno => 63, :name => "マスターオブ整数", :price => 1182, :publisher => "東京出版", :level => 6, :hands => 2, :layout => 3, :const => 4, :page => 112)
Book.create(:jpgno => 64, :name => "ハイレベル理系数学", :price => 1426, :publisher => "河合出版", :level => 6, :hands => 2, :layout => 2, :const => 4, :page => 342)
Book.create(:jpgno => 65, :name => "理系数学良問プラチカ3", :price => 1080, :publisher => "河合出版", :level => 6, :hands => 3, :layout => 2, :const => 4, :page => 168)
Book.create(:jpgno => 66, :name => "医学部攻略の数学", :price => 1728, :publisher => "河合出版", :level => 6, :hands => 3, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 67, :name => "理系数学入試の核心難関大編", :price => 1296, :publisher => "Z会出版", :level => 6, :hands => 3, :layout => 4, :const => 5, :page => 206)
Book.create(:jpgno => 68, :name => "チャート式数学難問集100", :price => 1296, :publisher => "数研出版", :level => 6, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 69, :name => "鉄緑会東大数学問題集30年分", :price => 4536, :publisher => "角川学芸出版", :level => 6, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 70, :name => "医学部良問セレクト77", :price => 1944, :publisher => "聖文新社", :level => 6, :hands => 3, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 71, :name => "入試数学伝説の良問100", :price => 1188, :publisher => "講談社ブルーバックス", :level => 6, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 72, :name => "入試数学の掌握", :price => 1620, :publisher => "エール出版", :level => 6, :hands => 2, :layout => 3, :const => 3, :page => 300)
Book.create(:jpgno => 73, :name => "厳選大学入試数学問題集文系", :price => 1080, :publisher => "河合出版", :level => 4, :hands => 1, :layout => 3, :const => 4, :page => 86)
